backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;


use common\models\User;
use frontend\models\ResendVerificationEmailForm;
use frontend\models\search\TestSearch;
use frontend\models\Test;
use frontend\models\VerifyEmailForm;
use Yii;
use yii\base\InvalidArgumentException;
use yii\helpers\Json;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['signup', 'login'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['index', 'logout', 'grid-view', 'modal-pjax',
                            'create-view', 'create', 'view', 'update-view', 'update', 'delete', 'list-view'],
                        'allow' => true,
                        'roles' => ['@'],
                        'denyCallback' => function () {
                            return Yii::$app->controller->redirect(['site/login']);
                        }
                    ],
                    [
                        'actions' => ['about'],
                        'allow' => AuthController::auth([User::ROLE_ADMIN, User::ROLE_USER, User::ROLE_ADMINS]),
                        'roles' => ['@'],
                        'denyCallback' => function () {
                            return Yii::$app->controller->redirect(['site/index']);
                        }
                    ],
                    [
                        'actions' => ['contact'],
                        'allow' => AuthController::auth([User::ROLE_ADMIN]),
                        'roles' => ['@'],
                        'denyCallback' => function () {
                            return Yii::$app->controller->redirect(['site/index']);
                        }
                    ],
                    [
                        'actions' => ['signup', 'login'],
                        'allow' => false,
                        'roles' => ['@'],
                        'denyCallback' => function () {
                            return Yii::$app->controller->redirect(['site/about']);
                        }
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['site/index']);
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['site/index']);
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->redirect(['site/login']);
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            $modelLogin = new LoginForm();
            $modelLogin->username = $model->username;
            $modelLogin->password = $model->password;
            if ($modelLogin->login()) {
                return $this->redirect(['site/index']);
            }
            Yii::$app->session->setFlash('success', 'Thank you for registration. Please check your inbox for verification email.');
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Verify email address
     *
     * @param string $token
     * @throws BadRequestHttpException
     * @return yii\web\Response
     */
    public function actionVerifyEmail($token)
    {
        try {
            $model = new VerifyEmailForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($user = $model->verifyEmail()) {
            if (Yii::$app->user->login($user)) {
                Yii::$app->session->setFlash('success', 'Your email has been confirmed!');
                return $this->goHome();
            }
        }

        Yii::$app->session->setFlash('error', 'Sorry, we are unable to verify your account with provided token.');
        return $this->goHome();
    }

    /**
     * Resend verification email
     *
     * @return mixed
     */
    public function actionResendVerificationEmail()
    {
        $model = new ResendVerificationEmailForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');
                return $this->goHome();
            }
            Yii::$app->session->setFlash('error', 'Sorry, we are unable to resend verification email for the provided email address.');
        }

        return $this->render('resendVerificationEmail', [
            'model' => $model
        ]);
    }


    public function actionGridView()
    {
        $searchModel = new TestSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('grid-view', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionListView()
    {
        $searchModel = new TestSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $TestSearch = Yii::$app->request->get('TestSearch');
//        return Json::encode($TestSearch);
        if($TestSearch['page_size']){
            $dataProvider->pagination->pageSize = $TestSearch['page_size'];
        }else{
            $dataProvider->pagination->pageSize = 5;
        }

        return $this->render('list-view', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionModalPjax()
    {
        $searchModel = new TestSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('modal-pjax', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

frontend/views/site/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="o1-rainfall-form">
    <?php $form = ActiveForm::begin(['id' => 'create-form']); ?>
    <?= Html::activeHiddenInput($model, '_id'); ?>
    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'a')->textInput() ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'b')->textInput() ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'c')->textInput() ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'd')->textInput() ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'e')->textInput() ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'f')->textInput() ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'g')->textInput() ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'h')->textInput() ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'i')->textInput() ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'j')->textInput() ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'k')->textInput() ?>
        </div>
    </div>
    <div class="form-group">
        <?= Html::submitButton('บันทึก', ['class' => 'btn btn-success']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

frontend/views/site/_list-view-item.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\widgets\Pjax;
use frontend\models\Test;

/* @var $this yii\web\View */


$this->title = 'My Yii Application';
?>
<div class="site-index">
    <div class="card-box">
        <div class="row">
            <div class="col-md-12">
                <div class="my-content">
                    <p class="my-topic">A : <?= $model->a ?></p>
                    <p class="my-topic">B : <?= $model->b ?></p>
                    <p class="my-topic">C : <?= $model->c ?></p>
                    <p class="my-topic">D : <?= $model->d ?></p>
                    <p class="my-topic">E : <?= $model->e ?></p>
                </div>
            </div>
        </div>
    </div>
</div>

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/grid-view.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\widgets\Pjax;
use frontend\models\Test;

/* @var $this yii\web\View */


$this->title = 'My Yii Application';
?>
<div class="site-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php Pjax::begin(['id' => 'pjax_index']); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'formatter' => [
            'class' => 'yii\i18n\Formatter',
            'nullDisplay' => '-'
        ],
        'columns' => [
            [
                'class' => 'yii\grid\SerialColumn',
                'contentOptions' => ['style' => 'min-width:40px;width:40px']],
            [
                'attribute' => 'a',
                'headerOptions' => ['style' => 'min-width:260px;'],
            ],
            [
                'attribute' => 'b',
                'filterType' => GridView::FILTER_SELECT2,
                'filter' => Test::getBArrayList(),
                'filterWidgetOptions' => [
                    'pluginOptions' => ['allowClear' => true],
                ],
                'filterInputOptions' => [
                    'placeholder' => 'ค้นหา b',
                    'multiple' => true,
                ],
                'headerOptions' => ['style' => 'min-width:260px;'],
                'value' => function ($model) {
                    return $model->b;
                }
            ],
            [
                'attribute' => 'c',
                'filterType' => GridView::FILTER_SELECT2,
                'filter' => Test::getCArrayList(),
                'filterWidgetOptions' => [
                    'pluginOptions' => ['allowClear' => true],
                ],
                'filterInputOptions' => [
                    'placeholder' => 'ค้นหา c',
                    'multiple' => true,
                ],
                'headerOptions' => ['style' => 'min-width:260px;'],
            ],
            [
                'attribute' => 'de',
                'label' => 'ค้นหา D และ E',
                'headerOptions' => ['style' => 'min-width:260px;'],
                'value' => function ($model) {
                    return $model->d . ' ' . $model->e;
                }
            ],
            'f',
            'g',
            'h',
            'i',
            'j',
            'k',
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\web\JqueryAsset;

$this->registerJsFile('@web/js/test.js', ['depends' => [JqueryAsset::className()]]);
$this->registerCssFile('@web/css/test.css', ['depends' => [JqueryAsset::className()]]);
$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>GridView yii2-grid</h2>
                <p><?= \yii\helpers\Html::a('GridView yii2-grid &raquo;', ['site/grid-view'], ['class' => 'btn btn-default']) ?></p>
            </div>
            <div class="col-lg-4">
                <h2>Modal Pjax</h2>
                <p><?= \yii\helpers\Html::a('Modal Pjax &raquo;', ['site/modal-pjax'], ['class' => 'btn btn-default']) ?></p>
            </div>
            <div class="col-lg-4">
                <h2>ListView yii2-list-view</h2>
                <p><?= \yii\helpers\Html::a('List View &raquo;', ['site/list-view'], ['class' => 'btn btn-default']) ?></p>
            </div>
        </div>

    </div>
</div>

frontend/views/site/list-view.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
use yii\widgets\ListView;
use kartik\select2\Select2;

/* @var $this yii\web\View */


$this->title = 'My Yii Application';
?>
<style>
    .my-content {
        height: 80px;
        border-radius: 5px;
        border: solid 1px #eeeeee;
        margin: 10px;
        box-shadow: 0px 0px 5px rgba(193, 193, 193, 0.65);
        display: flex;
        padding: 20px;
    }

    .my-topic {
        display: flex;
        align-self: center;
        width: 20%;
    }
</style>
<div class="site-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin(['id' => 'create-form']); ?>
    <div class="row">
        <div class="col-md-12">
            <?= $form->field($searchModel, 'global_search',['options'=>['style'=>'display:inline-block;width:79%']])->textInput() ?>
            <div class="form-group" style="display:inline-block;width: 20%">
                <?= Html::button('Search', ['class' => 'btn btn-success', 'id' => 'my-search']) ?>
            </div>
        </div>

    </div>

    <div class="row">
        <div class="col-md-12">
            <?= $form->field($searchModel, 'page_size',['options'=>['style'=>'width:100px']])->widget(Select2::classname(), [
                'data' => [2 => 2, 5 => 5, 10 => 10, 15 => 15, 20 => 20],
                'options' => ['placeholder' => 'pageSize'],
                'pluginOptions' => [
                    'allowClear' => true,
                ],
            ])->label('Page Size');
            ?>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
    <?php Pjax::begin(['id' => 'pjax_index']); ?>
    <?php
    echo ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_list-view-item',
        'summary' => '',
    ]);
    ?>
    <?php Pjax::end(); ?>
</div>
<?php
$js = <<<JS
$(document).delegate('#testsearch-page_size', 'change',function (event) {
    event.preventDefault();
    let pageSize = $('#testsearch-page_size').val();
    let keyword = $('#testsearch-global_search').val();
    $.pjax.reload({
        container: '#pjax_index',
        'timeout': 2500,
        'url': 'list-view?TestSearch[global_search]=' + keyword + '&TestSearch[page_size]=' + pageSize
    });
});

$(document).delegate('#my-search', 'click',function (event) {
    event.preventDefault();
    let pageSize = $('#testsearch-page_size').val();
    let keyword = $('#testsearch-global_search').val();
    $.pjax.reload({
    container: '#pjax_index',
        'timeout': 2500,
        'url': 'list-view?TestSearch[global_search]=' + keyword + '&TestSearch[page_size]=' + pageSize
    });
});
JS;
$this->registerJs($js);
?>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>
    <?= Yii::$app->request->csrfToken ?>
    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

            <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'password')->passwordInput() ?>

            <?= $form->field($model, 'rememberMe')->checkbox() ?>

            <div style="color:#999;margin:1em 0">
                If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                <br>
                Need new verification email? <?= Html::a('Resend', ['site/resend-verification-email']) ?>
            </div>

            <div class="form-group">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/modal-pjax.php
<?php

use yii\bootstrap\Modal;
use yii\helpers\Html;
use kartik\grid\GridView;
use yii\web\JqueryAsset;
use yii\widgets\Pjax;
use frontend\models\Test;

/* @var $this yii\web\View */
$this->registerJsFile('@web/js/modalTest.js', ['depends' => [JqueryAsset::className()]]);

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::button('<i class="fa fa-plus"></i> ' . 'เพิ่ม', ['class' => 'btn btn-success', 'id' => 'create-data']) ?>
    </p>
    <?php Pjax::begin(['id' => 'pjax_index']); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'formatter' => [
            'class' => 'yii\i18n\Formatter',
            'nullDisplay' => '-'
        ],
        'columns' => [
            [
                'class' => 'yii\grid\SerialColumn',
                'contentOptions' => ['style' => 'min-width:40px;width:40px']],
            [
                'attribute' => 'a',
                'headerOptions' => ['style' => 'min-width:260px;'],
            ],
            [
                'attribute' => 'b',
                'filterType' => GridView::FILTER_SELECT2,
                'filter' => Test::getBArrayList(),
                'filterWidgetOptions' => [
                    'pluginOptions' => ['allowClear' => true],
                ],
                'filterInputOptions' => [
                    'placeholder' => 'ค้นหา b',
                ],
                'headerOptions' => ['style' => 'min-width:260px;'],
            ],
            [
                'attribute' => 'c',
                'filterType' => GridView::FILTER_SELECT2,
                'filter' => Test::getCArrayList(),
                'filterWidgetOptions' => [
                    'pluginOptions' => ['allowClear' => true],
                ],
                'filterInputOptions' => [
                    'placeholder' => 'ค้นหา c',
                    'multiple' => true,
                ],
                'headerOptions' => ['style' => 'min-width:260px;'],
            ],
            [
                'attribute' => 'de',
                'label' => 'ค้นหา D และ E',
                'headerOptions' => ['style' => 'min-width:260px;'],
                'value' => function ($model) {
                    return $model->d . ' ' . $model->e;
                }
            ],
            'f',
            'g',
            'h',
            'i',
            'j',
            'k',
            [
                'class' => 'yii\grid\ActionColumn',
                'header' => 'ดำเนินการ',
                'headerOptions' => ['style' => 'text-align: center;width:90px;min-width:90px'],
                'template' => '<div class="btn-group btn-group-sm text-center" style="display: block;text-align: center;" role="group">{view} {update} {delete}</div>',
                'buttons' => [
                    'view' => function ($url, $model, $key) {
                        return Html::a('<i class="glyphicon glyphicon-eye-open blue"></i>', ['site/modal-pjax'], [
                            'class' => 'view',
                            'style' => 'margin:0px 3px',
                            'data-id' => $key,
                        ]);
                    },
                    'update' => function ($url, $model, $key) {
                        return Html::a('<i class="glyphicon glyphicon-pencil green"></i>', ['site/modal-pjax'], [
                            'class' => 'update',
                            'style' => 'margin:0px 3px',
                            'data-id' => $key,
                        ]);
                    },
                    'delete' => function ($url, $model, $key) {
                        return Html::a('<i class="glyphicon glyphicon-trash red"></i>', ['site/modal-pjax'], [
                            'class' => 'delete',
                            'style' => 'margin:0px 3px',
                            'data-id' => $key,
                        ]);
                    }
                ],
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>
<?php Modal::begin([
    'id' => 'control-modal',
    'header' => '<h4 class="modal-title"></h4>',
    'size' => 'modal-lg',
    'clientOptions' => ['backdrop' => true],
    'footer' => null,
    'options' => [
        'tabindex' => false,
    ],
]);
Modal::end();
?>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resendVerificationEmail.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Resend verification email';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-resend-verification-email">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A verification email will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'resend-verification-email-form']); ?>

            <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

            <div class="form-group">
                <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>